### ISSUE TITLE
Metadata Crash (With "Fixed" Jar)

### ISSUE THREAD

**Issue by CobaltSparkz** [CyberdyneCC/BigReactors#15]
Hey! A while back spoke with Tomson and got a custom Jar (version 0.4.3A) to resolve the Metadata crashing issue. Still crashing D: 

http://pastebin.com/PhSWz9f2

Thanks!

**Comment by XFactHD** [comment]
Thanks for the report, I will look into it again ASAP.

**Comment by XFactHD** [comment]
@Robotia Damn, you were faster :)

**Comment by Robotia** [comment]
Haha sorry about that, I didn't read the comments underneath it :confused: 

I'll be more careful in the future :smiley:

**Comment by XFactHD** [comment]
No problem, this would have had to wait some days anyways, so it definitely better this way.

**Comment by CobaltSparkz** [comment]
Time for monster derping question - Where's the fix that I can use, that matches version 0.4.3A, as I'm using pre-made packs, such as RR3 Mainline, Infinity Evolved, CrundeeCraft e.t.c? D:

**Comment by XFactHD** [comment]
For the fix to work, the fixed would need to be installed on the server.

**Comment by CobaltSparkz** [comment]
Is it possible to get a version of the "fixed" Jar? I've got a migraine today, apologies for the brain-dead questions D:

**Comment by XFactHD** [comment]
I can't build it for you right now but maybe @Robotia can do it.

**Comment by Eufranio** [comment]
rip
