### ISSUE TITLE
1.8 Port

### ISSUE THREAD

**Issue by SunDwarf** [CyberdyneCC/BigReactors#2]
Since you're working on this again, I assume, is there any plans for a 1.8.9 port?

If there isn't, I'd be more than willing to help make one

**Comment by Tomson124** [comment]
As far as I know someone is already trying to port it to 1.8.9 But without CoFHCore updating, there is no real way to port it to 1.8.9
BTW Minecraft 1.9 will be released really soon ;)

**Comment by Cracks777** [comment]
buildcraft has been updated to 1.8? it uses rf

**Comment by Tomson124** [comment]
There is no dependency of CofHCore in their source files... Don't know how they are doing that, but I didn't find a version of CofHCore for 1.8.9

**Comment by SunDwarf** [comment]
There's no COFHCore, but there is an RF API available.

**Comment by Tomson124** [comment]
That makes sense though...
For a future 1.8 release of the mod you can look into this one: https://github.com/modmuss50/BigReactors-2
But this guy is still working on it and it will take some time...
