### ISSUE TITLE
[BUG] Fluid fuel to water bug

### ISSUE THREAD

**Issue by spannerman79** [CyberdyneCC/BigReactors#9]
Forge 1614
https://github.com/CyberdyneCC/BigReactors/releases/tag/v0.4.5B

I think this shows the issue fully

https://www.youtube.com/watch?v=5RpFun2pi3A

**Comment by XFactHD** [comment]
Mr E. Beef didn't fully implement those fluids and one of us is in the progress of implementing the rest of the fluid fuel system which will take some time.
Also, in one of the older issues, Mr E. Beef said that the fluids were only intended to be used internally for calculations in the reactor and not to be obtained by the player.

**Comment by bookerthegeek** [comment]
He did, as the issue is raised by the fact you can smelt the fluid in a smelter it is an issue with tinkers. Best bet is to remove the smelting of it from the smeltery with Mod tweaker as Tinkers Construct is EoL for 1.7.10

**Comment by spannerman79** [comment]
> Tinkers Construct

I am not using Tinkers Construct

**Comment by bookerthegeek** [comment]
Thinkers was an example,  others mods also do the same thing AoBD for example.

Can I get a mod list?

**Comment by spannerman79** [comment]
````
  BigReactors-0.4.5B
  CoFHCore-[1.7.10]3.1.2-325
````

When I test a mod or diagnose an issue i isolate the mod.  Which i have.

**Comment by bookerthegeek** [comment]
My apologies.  ;)

**Comment by Tomson124** [comment]
Just tested the thing in my dev environment, and yes it is a issue with BigReactors, but I don't really have time to look into it, I'm doing my A levles atm. Maybe someone else from CCC can look into fixing it in the meantime :)

**Comment by Robotia** [comment]
Just took a look at the code and found this in BRLoader:
```java
        @SubscribeEvent
    public void onBucketFill(FillBucketEvent e)
    {
        if(e.current.getItem() != Items.bucket)
        {
            return;
        }
        ItemStack filledBucket = fillBucket(e.world, e.target);
        if(filledBucket != null)
        {
            e.world.setBlockToAir(e.target.blockX, e.target.blockY, e.target.blockZ);
            e.result = filledBucket;
            e.setResult(Result.ALLOW);
        }
    }
```
In theory, it should be picked up by the Bucket. Perhaps the event is not actually being called?

**Comment by bookerthegeek** [comment]
I believe mod author stated he never fully implemented the fluid as a forge fluid, such that when bucketed it turns into a water bucket, or something like that. I'll look and see if I can find the issue it was stated in.

**Comment by Robotia** [comment]
Actually.. @bookerthegeek I think I just hit the jackpot, my hunch was right I believe. The event is in the wrong file and will never be called by Forge. It should've been in BREventHandler, making a commit as we speak.

**Comment by bookerthegeek** [comment]
😝

**Comment by Robotia** [comment]
From the code, I could see he had followed the tutorial given by MinecraftForge, but he put it in the wrong file. BRLoader cannot handle events because it was never registered on the EVENT_BUS, but BREventHandler is.

**Comment by Robotia** [comment]
For reference:
